#!/bin/bash
hexstate=1
rm 2048game.log
while ./2048play $hexstate 2>> 2048game.log; do
  hexstate=`tail -2 2048game.log | head -1 | sed -e "s/[^0-9a-fA-F]//"`
  mv 2048game.log 2048game.prv
  head -n -1 < 2048game.prv > 2048game.log
  rm 2048game.prv
done
