#define ENABLE_RA0_PULLUP() _CN2PUE = 1
#define DISABLE_RA0_PULLUP() _CN2PUE = 0
#define ENABLE_RA1_PULLUP() _CN3PUE = 1
#define DISABLE_RA1_PULLUP() _CN3PUE = 0
#define ENABLE_RA2_PULLUP() _CN30PUE = 1
#define DISABLE_RA2_PULLUP() _CN30PUE = 0
#define ENABLE_RA3_PULLUP() _CN29PUE = 1
#define DISABLE_RA3_PULLUP() _CN29PUE = 0
#define ENABLE_RA4_PULLUP() _CN0PUE = 1
#define DISABLE_RA4_PULLUP() _CN0PUE = 0
#define ENABLE_RB0_PULLUP() _CN4PUE = 1
#define DISABLE_RB0_PULLUP() _CN4PUE = 0
#define ENABLE_RB1_PULLUP() _CN5PUE = 1
#define DISABLE_RB1_PULLUP() _CN5PUE = 0
#define ENABLE_RB4_PULLUP() _CN1PUE = 1
#define DISABLE_RB4_PULLUP() _CN1PUE = 0
#define ENABLE_RB7_PULLUP() _CN23PUE = 1
#define DISABLE_RB7_PULLUP() _CN23PUE = 0
#define ENABLE_RB8_PULLUP() _CN22PUE = 1
#define DISABLE_RB8_PULLUP() _CN22PUE = 0
#define ENABLE_RB9_PULLUP() _CN21PUE = 1
#define DISABLE_RB9_PULLUP() _CN21PUE = 0
#define ENABLE_RB14_PULLUP() _CN12PUE = 1
#define DISABLE_RB14_PULLUP() _CN12PUE = 0
#define ENABLE_RB15_PULLUP() _CN11PUE = 1
#define DISABLE_RB15_PULLUP() _CN11PUE = 0
#define ENABLE_RA0_CN_INTERRUPT() _CN2IE = 1
#define DISABLE_RA0_CN_INTERRUPT() _CN2IE = 0
#define ENABLE_RA1_CN_INTERRUPT() _CN3IE = 1
#define DISABLE_RA1_CN_INTERRUPT() _CN3IE = 0
#define ENABLE_RA2_CN_INTERRUPT() _CN30IE = 1
#define DISABLE_RA2_CN_INTERRUPT() _CN30IE = 0
#define ENABLE_RA3_CN_INTERRUPT() _CN29IE = 1
#define DISABLE_RA3_CN_INTERRUPT() _CN29IE = 0
#define ENABLE_RA4_CN_INTERRUPT() _CN0IE = 1
#define DISABLE_RA4_CN_INTERRUPT() _CN0IE = 0
#define ENABLE_RB0_CN_INTERRUPT() _CN4IE = 1
#define DISABLE_RB0_CN_INTERRUPT() _CN4IE = 0
#define ENABLE_RB1_CN_INTERRUPT() _CN5IE = 1
#define DISABLE_RB1_CN_INTERRUPT() _CN5IE = 0
#define ENABLE_RB4_CN_INTERRUPT() _CN1IE = 1
#define DISABLE_RB4_CN_INTERRUPT() _CN1IE = 0
#define ENABLE_RB7_CN_INTERRUPT() _CN23IE = 1
#define DISABLE_RB7_CN_INTERRUPT() _CN23IE = 0
#define ENABLE_RB8_CN_INTERRUPT() _CN22IE = 1
#define DISABLE_RB8_CN_INTERRUPT() _CN22IE = 0
#define ENABLE_RB9_CN_INTERRUPT() _CN21IE = 1
#define DISABLE_RB9_CN_INTERRUPT() _CN21IE = 0
#define ENABLE_RB14_CN_INTERRUPT() _CN12IE = 1
#define DISABLE_RB14_CN_INTERRUPT() _CN12IE = 0
#define ENABLE_RB15_CN_INTERRUPT() _CN11IE = 1
#define DISABLE_RB15_CN_INTERRUPT() _CN11IE = 0
#define DISABLE_RA0_ANALOG() _PCFG0 = 1
#define ENABLE_RA0_ANALOG() _PCFG0 = 0
#define DISABLE_RA1_ANALOG() _PCFG1 = 1
#define ENABLE_RA1_ANALOG() _PCFG1 = 0
#define DISABLE_RB0_ANALOG() _PCFG2 = 1
#define ENABLE_RB0_ANALOG() _PCFG2 = 0
#define DISABLE_RB1_ANALOG() _PCFG3 = 1
#define ENABLE_RB1_ANALOG() _PCFG3 = 0
#define DISABLE_RB14_ANALOG() _PCFG7 = 1
#define ENABLE_RB14_ANALOG() _PCFG7 = 0
#define DISABLE_RB15_ANALOG() _PCFG6 = 1
#define ENABLE_RB15_ANALOG() _PCFG6 = 0
#define ENABLE_RA0_OPENDRAIN() _ODCA0 = 1
#define DISABLE_RA0_OPENDRAIN() _ODCA0 = 0
#define ENABLE_RA1_OPENDRAIN() _ODCA1 = 1
#define DISABLE_RA1_OPENDRAIN() _ODCA1 = 0
#define ENABLE_RA2_OPENDRAIN() _ODCA2 = 1
#define DISABLE_RA2_OPENDRAIN() _ODCA2 = 0
#define ENABLE_RA3_OPENDRAIN() _ODCA3 = 1
#define DISABLE_RA3_OPENDRAIN() _ODCA3 = 0
#define ENABLE_RA4_OPENDRAIN() _ODCA4 = 1
#define DISABLE_RA4_OPENDRAIN() _ODCA4 = 0
#define ENABLE_RB0_OPENDRAIN() _ODCB0 = 1
#define DISABLE_RB0_OPENDRAIN() _ODCB0 = 0
#define ENABLE_RB1_OPENDRAIN() _ODCB1 = 1
#define DISABLE_RB1_OPENDRAIN() _ODCB1 = 0
#define ENABLE_RB4_OPENDRAIN() _ODCB4 = 1
#define DISABLE_RB4_OPENDRAIN() _ODCB4 = 0
#define ENABLE_RB7_OPENDRAIN() _ODCB7 = 1
#define DISABLE_RB7_OPENDRAIN() _ODCB7 = 0
#define ENABLE_RB8_OPENDRAIN() _ODCB8 = 1
#define DISABLE_RB8_OPENDRAIN() _ODCB8 = 0
#define ENABLE_RB9_OPENDRAIN() _ODCB9 = 1
#define DISABLE_RB9_OPENDRAIN() _ODCB9 = 0
#define ENABLE_RB14_OPENDRAIN() _ODCB14 = 1
#define DISABLE_RB14_OPENDRAIN() _ODCB14 = 0
#define ENABLE_RB15_OPENDRAIN() _ODCB15 = 1
#define DISABLE_RB15_OPENDRAIN() _ODCB15 = 0
static inline void CONFIG_RA0_AS_DIG_OUTPUT() {
  DISABLE_RA0_PULLUP();
  DISABLE_RA0_OPENDRAIN();
  _TRISA0 = 0;
  _PCFG0 = 1;
}
static inline void CONFIG_RA1_AS_DIG_OUTPUT() {
  DISABLE_RA1_PULLUP();
  DISABLE_RA1_OPENDRAIN();
  _TRISA1 = 0;
  _PCFG1 = 1;
}
static inline void CONFIG_RA2_AS_DIG_OUTPUT() {
  DISABLE_RA2_PULLUP();
  DISABLE_RA2_OPENDRAIN();
  _TRISA2 = 0;
}
static inline void CONFIG_RA3_AS_DIG_OUTPUT() {
  DISABLE_RA3_PULLUP();
  DISABLE_RA3_OPENDRAIN();
  _TRISA3 = 0;
}
static inline void CONFIG_RA4_AS_DIG_OUTPUT() {
  DISABLE_RA4_PULLUP();
  DISABLE_RA4_OPENDRAIN();
  _TRISA4 = 0;
}
static inline void CONFIG_RB0_AS_DIG_OUTPUT() {
  DISABLE_RB0_PULLUP();
  DISABLE_RB0_OPENDRAIN();
  _TRISB0 = 0;
  _PCFG2 = 1;
}
static inline void CONFIG_RB1_AS_DIG_OUTPUT() {
  DISABLE_RB1_PULLUP();
  DISABLE_RB1_OPENDRAIN();
  _TRISB1 = 0;
  _PCFG3 = 1;
}
static inline void CONFIG_RB4_AS_DIG_OUTPUT() {
  DISABLE_RB4_PULLUP();
  DISABLE_RB4_OPENDRAIN();
  _TRISB4 = 0;
}
static inline void CONFIG_RB7_AS_DIG_OUTPUT() {
  DISABLE_RB7_PULLUP();
  DISABLE_RB7_OPENDRAIN();
  _TRISB7 = 0;
}
static inline void CONFIG_RB8_AS_DIG_OUTPUT() {
  DISABLE_RB8_PULLUP();
  DISABLE_RB8_OPENDRAIN();
  _TRISB8 = 0;
}
static inline void CONFIG_RB9_AS_DIG_OUTPUT() {
  DISABLE_RB9_PULLUP();
  DISABLE_RB9_OPENDRAIN();
  _TRISB9 = 0;
}
static inline void CONFIG_RB14_AS_DIG_OUTPUT() {
  DISABLE_RB14_PULLUP();
  DISABLE_RB14_OPENDRAIN();
  _TRISB14 = 0;
  _PCFG7 = 1;
}
static inline void CONFIG_RB15_AS_DIG_OUTPUT() {
  DISABLE_RB15_PULLUP();
  DISABLE_RB15_OPENDRAIN();
  _TRISB15 = 0;
  _PCFG6 = 1;
}
static inline void CONFIG_RA0_AS_DIG_OD_OUTPUT() {
  DISABLE_RA0_PULLUP();
  ENABLE_RA0_OPENDRAIN();
  _TRISA0 = 0;
  _PCFG0 = 1;
}
static inline void CONFIG_RA1_AS_DIG_OD_OUTPUT() {
  DISABLE_RA1_PULLUP();
  ENABLE_RA1_OPENDRAIN();
  _TRISA1 = 0;
  _PCFG1 = 1;
}
static inline void CONFIG_RA2_AS_DIG_OD_OUTPUT() {
  DISABLE_RA2_PULLUP();
  ENABLE_RA2_OPENDRAIN();
  _TRISA2 = 0;
}
static inline void CONFIG_RA3_AS_DIG_OD_OUTPUT() {
  DISABLE_RA3_PULLUP();
  ENABLE_RA3_OPENDRAIN();
  _TRISA3 = 0;
}
static inline void CONFIG_RA4_AS_DIG_OD_OUTPUT() {
  DISABLE_RA4_PULLUP();
  ENABLE_RA4_OPENDRAIN();
  _TRISA4 = 0;
}
static inline void CONFIG_RB0_AS_DIG_OD_OUTPUT() {
  DISABLE_RB0_PULLUP();
  ENABLE_RB0_OPENDRAIN();
  _TRISB0 = 0;
  _PCFG2 = 1;
}
static inline void CONFIG_RB1_AS_DIG_OD_OUTPUT() {
  DISABLE_RB1_PULLUP();
  ENABLE_RB1_OPENDRAIN();
  _TRISB1 = 0;
  _PCFG3 = 1;
}
static inline void CONFIG_RB4_AS_DIG_OD_OUTPUT() {
  DISABLE_RB4_PULLUP();
  ENABLE_RB4_OPENDRAIN();
  _TRISB4 = 0;
}
static inline void CONFIG_RB7_AS_DIG_OD_OUTPUT() {
  DISABLE_RB7_PULLUP();
  ENABLE_RB7_OPENDRAIN();
  _TRISB7 = 0;
}
static inline void CONFIG_RB8_AS_DIG_OD_OUTPUT() {
  DISABLE_RB8_PULLUP();
  ENABLE_RB8_OPENDRAIN();
  _TRISB8 = 0;
}
static inline void CONFIG_RB9_AS_DIG_OD_OUTPUT() {
  DISABLE_RB9_PULLUP();
  ENABLE_RB9_OPENDRAIN();
  _TRISB9 = 0;
}
static inline void CONFIG_RB14_AS_DIG_OD_OUTPUT() {
  DISABLE_RB14_PULLUP();
  ENABLE_RB14_OPENDRAIN();
  _TRISB14 = 0;
  _PCFG7 = 1;
}
static inline void CONFIG_RB15_AS_DIG_OD_OUTPUT() {
  DISABLE_RB15_PULLUP();
  ENABLE_RB15_OPENDRAIN();
  _TRISB15 = 0;
  _PCFG6 = 1;
}
static inline void CONFIG_RA0_AS_DIG_INPUT() {
  DISABLE_RA0_PULLUP();
  _TRISA0 = 1;
  _PCFG0 = 1;
}
static inline void CONFIG_RA1_AS_DIG_INPUT() {
  DISABLE_RA1_PULLUP();
  _TRISA1 = 1;
  _PCFG1 = 1;
}
static inline void CONFIG_RA2_AS_DIG_INPUT() {
  DISABLE_RA2_PULLUP();
  _TRISA2 = 1;
}
static inline void CONFIG_RA3_AS_DIG_INPUT() {
  DISABLE_RA3_PULLUP();
  _TRISA3 = 1;
}
static inline void CONFIG_RA4_AS_DIG_INPUT() {
  DISABLE_RA4_PULLUP();
  _TRISA4 = 1;
}
static inline void CONFIG_RB0_AS_DIG_INPUT() {
  DISABLE_RB0_PULLUP();
  _TRISB0 = 1;
  _PCFG2 = 1;
}
static inline void CONFIG_RB1_AS_DIG_INPUT() {
  DISABLE_RB1_PULLUP();
  _TRISB1 = 1;
  _PCFG3 = 1;
}
static inline void CONFIG_RB4_AS_DIG_INPUT() {
  DISABLE_RB4_PULLUP();
  _TRISB4 = 1;
}
static inline void CONFIG_RB7_AS_DIG_INPUT() {
  DISABLE_RB7_PULLUP();
  _TRISB7 = 1;
}
static inline void CONFIG_RB8_AS_DIG_INPUT() {
  DISABLE_RB8_PULLUP();
  _TRISB8 = 1;
}
static inline void CONFIG_RB9_AS_DIG_INPUT() {
  DISABLE_RB9_PULLUP();
  _TRISB9 = 1;
}
static inline void CONFIG_RB14_AS_DIG_INPUT() {
  DISABLE_RB14_PULLUP();
  _TRISB14 = 1;
  _PCFG7 = 1;
}
static inline void CONFIG_RB15_AS_DIG_INPUT() {
  DISABLE_RB15_PULLUP();
  _TRISB15 = 1;
  _PCFG6 = 1;
}
#define CONFIG_RP0_AS_DIG_PIN()  _PCFG2 = 1
#define CONFIG_RP1_AS_DIG_PIN()  _PCFG3 = 1
#define CONFIG_RP2_AS_DIG_PIN()
#define CONFIG_RP3_AS_DIG_PIN()
#define CONFIG_RP4_AS_DIG_PIN()
#define CONFIG_RP5_AS_DIG_PIN()
#define CONFIG_RP6_AS_DIG_PIN()
#define CONFIG_RP7_AS_DIG_PIN()
#define CONFIG_RP8_AS_DIG_PIN()
#define CONFIG_RP9_AS_DIG_PIN()
#define CONFIG_RP10_AS_DIG_PIN()
#define CONFIG_RP11_AS_DIG_PIN()
#define CONFIG_RP12_AS_DIG_PIN()
#define CONFIG_RP13_AS_DIG_PIN()
#define CONFIG_RP14_AS_DIG_PIN()  _PCFG7 = 1
#define CONFIG_RP15_AS_DIG_PIN()  _PCFG6 = 1
#define CONFIG_RP16_AS_DIG_PIN()
#define CONFIG_RP17_AS_DIG_PIN()
#define CONFIG_RP18_AS_DIG_PIN()
#define CONFIG_RP19_AS_DIG_PIN()
#define CONFIG_RP20_AS_DIG_PIN()
#define CONFIG_RP21_AS_DIG_PIN()
#define CONFIG_RP22_AS_DIG_PIN()
#define CONFIG_RP23_AS_DIG_PIN()
#define CONFIG_RP24_AS_DIG_PIN()
#define CONFIG_RP25_AS_DIG_PIN()
#define CONFIG_RP26_AS_DIG_PIN()
#define CONFIG_RP27_AS_DIG_PIN()
#define CONFIG_RP28_AS_DIG_PIN()
#define CONFIG_RP29_AS_DIG_PIN()
#define CONFIG_RP30_AS_DIG_PIN()
#define CONFIG_RP31_AS_DIG_PIN()
#define CONFIG_RP32_AS_DIG_PIN()
#define CONFIG_RP33_AS_DIG_PIN()
#define CONFIG_RP34_AS_DIG_PIN()
#define CONFIG_RP35_AS_DIG_PIN()
#define CONFIG_RP36_AS_DIG_PIN()
#define CONFIG_RP37_AS_DIG_PIN()
#define CONFIG_RP38_AS_DIG_PIN()
#define CONFIG_RP39_AS_DIG_PIN()
#define CONFIG_RP40_AS_DIG_PIN()
#define CONFIG_RP41_AS_DIG_PIN()
#define CONFIG_RP42_AS_DIG_PIN()
#define CONFIG_RP43_AS_DIG_PIN()
#define CONFIG_RP44_AS_DIG_PIN()
#define CONFIG_RP45_AS_DIG_PIN()
#ifdef _PCFG0
static inline void CONFIG_AN0_AS_ANALOG() {
  CONFIG_RA0_AS_DIG_INPUT();
  _PCFG0 = 0;
}
#endif
#ifdef _PCFG1
static inline void CONFIG_AN1_AS_ANALOG() {
  CONFIG_RA1_AS_DIG_INPUT();
  _PCFG1 = 0;
}
#endif
#ifdef _PCFG2
static inline void CONFIG_AN2_AS_ANALOG() {
  CONFIG_RB0_AS_DIG_INPUT();
  _PCFG2 = 0;
}
#endif
#ifdef _PCFG3
static inline void CONFIG_AN3_AS_ANALOG() {
  CONFIG_RB1_AS_DIG_INPUT();
  _PCFG3 = 0;
}
#endif
#ifdef _PCFG4
static inline void CONFIG_AN4_AS_ANALOG() {
  _PCFG4 = 0;
}
#endif
#ifdef _PCFG5
static inline void CONFIG_AN5_AS_ANALOG() {
  _PCFG5 = 0;
}
#endif
#ifdef _PCFG6
static inline void CONFIG_AN6_AS_ANALOG() {
  CONFIG_RB15_AS_DIG_INPUT();
  _PCFG6 = 0;
}
#endif
#ifdef _PCFG7
static inline void CONFIG_AN7_AS_ANALOG() {
  CONFIG_RB14_AS_DIG_INPUT();
  _PCFG7 = 0;
}
#endif
#ifdef _PCFG8
static inline void CONFIG_AN8_AS_ANALOG() {
  _PCFG8 = 0;
}
#endif
#ifdef _PCFG9
static inline void CONFIG_AN9_AS_ANALOG() {
  _PCFG9 = 0;
}
#endif
#ifdef _PCFG10
static inline void CONFIG_AN10_AS_ANALOG() {
  _PCFG10 = 0;
}
#endif
#ifdef _PCFG11
static inline void CONFIG_AN11_AS_ANALOG() {
  _PCFG11 = 0;
}
#endif
#ifdef _PCFG12
static inline void CONFIG_AN12_AS_ANALOG() {
  _PCFG12 = 0;
}
#endif
#define _PIC24_DIGIO_DEFINED
